DRAFT: Dmytro/int 1847 UI improvement for target path folder selection
codemod-com/intuita-vscode-extension pull request #821
Opened 2023-09-19 17:07 UTC by DmytroHryshyn

2024-01-15 13:52 UTC, GeorgeWL commented on intuita-webview/src/codemodList/components/DirectorySelector.tsx
> +	console.log(defaultValue, '?');
never leave in console logs

2024-01-15 13:54 UTC, GeorgeWL requested changes
I don't really see the purpose of this PR tbh

2024-01-29 13:49 UTC, hbjORbj approved these changes

2024-01-29 14:07 UTC, grzpab commented on package.json
> +		"glob": "^10.3.4",
if we update the version, I think we should switch to `fast-glob`

2024-01-29 14:42 UTC, grzpab approved these changes

2024-01-29 14:53 UTC, DmytroHryshyn commented on intuita-webview/src/codemodList/CodemodArguments/index.tsx
> -const handleCodemodPathChange = debounce((rawCodemodPath: string) => {
debounce is no more needed because we only update path when user selects a new path in the dropdown selector.

2024-01-29 14:54 UTC, merged